AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'spec/dummy/**/*'

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 120

